### PR TITLE
adding template for documentation

### PR DESCRIPTION
**Pull request by vsoch**
This is a jekyll template that will render the sourcecred docs beautifully on GitHub pages. The documentation includes search, branding for SourceCred (with some colors made brighter to look better on the page), a news feed where announcements can go, a sidebar navigation (left) with a nested list of specific links of interest, a page navigation (right) to take the user to permalinks on the page, and a top navigation for basic about, documentation, and search pages. The GitHub repository with stars is in the upper right, along with links for social media (Twitter and GitHub) on the bottom. Finally, a circleci preview is added so that a contributor does not need to render the site locally.

This repository will need to be connected to CircleCI to generate the preview. I'll include screen shots below until then. Anyone is also able to clone and `bundle exec jekyll serve` - I've included complete developer documentation for how to do this in the README.md

The main front page

image

Documentation Index

image

Search example

image

Page rendering 

image

News feed (for updates to docs, anything we need really)

image

An example post

image

Tags index

image

I think that's it! I hope you like it :) 

Signed-off-by: vsoch <vsochat@stanford.edu>

### CODE REVIEW

**Comment by vsoch** [comment]
I could move the circle config to another PR, but I added it in the first place so this one _could_ be easily tested. I don’t see how to break up the changes to the docs, however, you can’t really review anything partial because it won’t render into the site...

**Comment by vsoch** [comment]
Done. I've opened the 10 PRs linked above. I don't understand how you can review without being able to render the site, but if that is your preference I respect that. Thanks for the reviews!

**Comment by decentralion** [comment]
Yeah, I see your point about this PR not splitting up cleanly. The 10 smaller PRs do feel artificial, i.e. they're mostly hard to test and review in isolation.

In my mind, the ideal flow would be something like:
1. Commit which adds in a basic out-of-the-box Jekyll installation without any configuration, i.e. it doesn't actually load our specific docs. Test plan: Verify that it renders the default "This is a new Jekyll instance!" type message.
2. Commit which re-organizes our directory structure so that the Jekyll loads our documentation. Test plan: confirm that it loads our documentation, but without the styling and theming that we want.
3. Add and use styling and theming that we want. This is the PR that I would review the most closely, and learn the most from, since now I'd be seeing the degrees of freedom that we (as maintainers of the docs) will want to exercise. Test plan: Visual inspection, etc.
4. README

The main advantage here would be that (for me as a reviewer) it would be easy to see what part of the PR is just standard Jekyll stuff (which I can approve with minimal investigation) and which part is customization for our use case. This would also make a clearer history in `git blame` for those who want to learn about the codebase and the customizations we made.

That said, I'm sympathetic if this feels like a ton of extra process-driven work to you. This review/commit flow has been really valuable for the core `sourcecred/sourcecred` codebase, where we care a great deal about refactor-ability, and making the code's history clear. However, for docs, refactor-ability and clear history are less important. So if you prefer, I can review this PR as-is (using the split apart PRs as a bit of a guide in looking at different parts of the code).

**Comment by vsoch** [comment]
> So if you prefer, I can review this PR as-is (using the split apart PRs as a bit of a guide in looking at different parts of the code).

Yes to this, and thank you! I understand the logic of this method for code, but for Jekyll, there really is no clear "clean slate" - it's mostly just a hairball until it's not. The issue with "creating a basic Jekyll site"  is that it would be very artificial to do - every one is a little different. A bare bones one wouldn't have the structure needed for our docs, so the PR would go in, and then most of the content would be erased. 

I know there is a lot of discussion around contributing, and barriers to contributing, and I understand the want for the commit history to be perfect, but it's coming at the cost of the sanity of the contributor. It might be easy for the pros of sourcecred to follow the rules as they know and like, but for some reason it's frustrating and feels very controlling for me every time. I'm very close to stopping my contributions because it's a stressful experience. Just something to think about. :/

**Comment by vsoch** [comment]
It looks like grain is missing here too - is there any easy way to add it back without totally redoing the PR?

**Comment by decentralion** [comment]
Carrying over from https://github.com/sourcecred/docs/pull/47#pullrequestreview-387985757:

I think Docasaurus is a better fit for the project than Jekyll. Because it's written in the same stack as sourcecred/sourcecred (node, react, etc) it will be easier for technical integrations (e.g. embedding SourceCred UI components directly in the docs) and present a smaller surface area for maintainers.

As such, I'm going to close this pull request. However, I appreciate the initiative that went into creating it. Also, exploring different technologies is valuable, including the explorations into the paths we don't take. To make sure we don't lose track of the value created here, I created a docs initiative which tracks this as a contribution, see: https://github.com/sourcecred/cred/pull/28

**Pull request closed without merging**
