### PR TITLE
Reorder FAQ page contents

### PR DESCRIPTION
**Pull request by KuraFire**
This Pull Request changes the order of the answers in the FAQ by quite a bit, making it one designed and streamlined whole. I've also made a couple of tiny tweaks to some of the answers, added and fixed some links, and formatted the whole thing as a headings-paragraphs document instead of a nested list, so that the right column now shows a table of contents for all of the questions. 

A preview can be seen here:
https://deploy-preview-244--sourcecred.netlify.app/docs/beta/faq/

PR Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by KuraFire** [comment]
Preview of this reorganized document can be seen here:
https://deploy-preview-244--sourcecred.netlify.app/docs/beta/faq/

**Comment by KuraFire** [comment]
In the future I'm going to not do such a massive reorganization of a document through a single save in the content manager (or maybe I'll just do it by hand), so that each step can be viewed via clean diffs and the changes seen more easily. Sorry about that.

**Review by Bex2594 — APPROVED** [review]
Love this, great thinking.

**Review by Bex2594 — COMMENTED** [review]
Love this, great thinking.

**Pull request merged**
