### PR TITLE
[glossary] adding draft of concept: deep then wide

### PR DESCRIPTION
**Pull request by vsoch**
This is the third PR to add concepts separately. For "deep then wide" (at least since I've joined the project) I've used it at least once, and I think having the definition is helpful. It's not totally intuitive to everyone what this means.

Signed-off-by: vsoch <vsochat@stanford.edu>

### CODE REVIEW

**Comment by decentralion** [comment]
Hmm, I'd like to propose some changes directly, specifically around adding another section explaining why we made the decision to go deep first. Would you mind editing this PR so that it's on a local branch rather than a fork, so I can push commits?

**Comment by vsoch** [comment]
Are you not able to push to my branch? I have "allow editors from maintainers" checked!

**Comment by wchargin** [comment]
(Also, it’s not possible to edit a PR to change the base ref across
forks or to change the head ref at all.)

**Comment by vsoch** [comment]
Alright, it's opened on this organization here! #22. I could leave it open (to close automatically on merge of the PR with shared commits) but I realize it's probably confusing having so many `[glossary]` PRs so I'm going to close manually.

**Pull request closed without merging**
