### PR TITLE
Moving and reorganizing markdown files with front end matter for jekyll

### PR DESCRIPTION
**Pull request by vsoch**
This is an artificially created PR to split #34 into smaller ones. This one just includes moving files with front end matter, and fixing headers to be consistent.

Signed-off-by: vsoch <vsochat@stanford.edu>

### CODE REVIEW

**Comment by decentralion** [comment]
Some questions: 
- Why was concepts/grain.md deleted? Maybe a merge/rebase type issue?
- Why the rename to `_docs`?
- A question I have had for a while: why is the concepts directory nested under community?

**Comment by vsoch** [comment]
I'm not sure about why grain was deleted, I'll open another PR and try again. For _docs, it's standard convention that a Jekyll collection is named with an underscore.

The third question seems out of scope for this change since it's already like that, but I think it happened because glossary was originally under community, and then concepts in the glossary are relative to that.

**Comment by vsoch** [comment]
I'm not sure about why grain was deleted, I'll open another PR and try again. For _docs, it's standard convention that a Jekyll collection is named with an underscore.

The third question seems out of scope for this change since it's already like that, but I think it happened because glossary was originally under community, and then concepts in the glossary are relative to that.

**Comment by vsoch** [comment]
Grain added https://github.com/sourcecred/docs/pull/45

**Pull request closed without merging**
