### PR TITLE
[glossary] Adding draft of concept: grain

### PR DESCRIPTION
**Pull request by vsoch**
As requested, this is the first of several PRs to allow for separate review of each concept.

Signed-off-by: vsoch <vsochat@stanford.edu>

### CODE REVIEW

**Comment by vsoch** [comment]
What are everyone's thoughts on verified commits? I haven't set up the automated signing of them yet on this machine, and I'm considering not doing it, at least, it's lots of extra typing that might be avoided. :)

**Comment by decentralion** [comment]
I'd like to re-write this section. Maybe make it a local branch rather than a fork so I can push commits? Or should I just open a new PR?

wrt verified commits, i personally don't really care. :)

**Comment by vsoch** [comment]
Closing in favor of https://github.com/sourcecred/docs/pull/23.

**Comment by vsoch** [comment]
I wound up giving in and generating the gpg key and having the setting to sign - I've done it for too long to go back now!

**Pull request closed without merging**
