### PR TITLE
Configure Docusaurus Static Site

### PR DESCRIPTION
**Pull request by hammadj**
This PR setups up [Docusaurus 2](https://v2.docusaurus.io) to render the docs files in a nice looking website. Alternative implementation to #34.

[Click here to see the live preview](https://sourcecred-docs.jutt.now.sh)

To add search, we first need to publish the site and then hook it up to [Algolia](https://docsearch.algolia.com/apply/) so it can crawl the pages and build up a content index. More details on how to enable search here: https://v2.docusaurus.io/docs/search/

This also includes an optional "blog". Not sure if this is something we want, but left it in here for demonstrative purposes. Was thinking it would be a good place to make public announcements on progress / releases / roadmap etc. Otherwise, I can remove it if we don't want it.

The site can be built and deployed to Github Pages. Can potentially use [this Github Action](https://github.com/clay/docusaurus-github-action), however that won't allow us to have a "deploy preview" in pull requests. If we deploy the site on Netlify/ZEIT Now instead, it will automatically handle all the build/deployment steps with zero config, including deploy previews. More information on how builds and deployments work here: https://v2.docusaurus.io/docs/deployment

Todo:
- [x] Improve README with better instructions on contributing
- [x] Remove blog, or cleanup the default content if we plan to use it

### CODE REVIEW

**Comment by vsoch** [comment]
It would be great to have a search that does not have an additional dependency of an alogia account - I had a similar situation a few months back for a search interface, was unable to find what was driving it, figured out it was alogia, and then refactored the code to remove that dependency (and use native metadata from GitHub pages to build an index). See https://vsoch.github.io/2020/github-search/ for the details. Needing to run a custom build for GitHub actions is another hassle, but if it's especially great one could argue that makes it better than native GitHub pages with Jekyll.

It's definitely a beautiful site! I love the icons in the sidebar.

**Comment by hammadj** [comment]
> It would be great to have a search that does not have an additional dependency of an alogia account - I had a similar situation a few months back for a search interface, was unable to find what was driving it, figured out it was alogia, and then refactored the code to remove that dependency (and use native metadata from GitHub pages to build an index). See https://vsoch.github.io/2020/github-search/ for the details. Needing to run a custom build for GitHub actions is another hassle, but if it's especially great one could argue that makes it better than native GitHub pages with Jekyll.
> 
> It's definitely a beautiful site! I love the icons in the sidebar.

If we don't want to use Algolia, we can roll our own as well: https://v2.docusaurus.io/docs/search#using-your-own-search

We don't NEED to run a GitHub actions build per se, can just build it before pushing it up and it will render in GitHub pages like usual, it's more for automating it and getting the deploy preview on PRs

**Comment by hammadj** [comment]
@decentralion For deployment, using Zeit Now or Netlify is probably the best bet. Can configure DNS settings so https://sourcecred.io points to this new deployment. Both of them will give live deployment previews on PRs. Its pretty straightforward to setup but LMK if you need help

**Comment by vsoch** [comment]
I appreciate the mention for copy pasting some of what I wrote, but I don’t think that actually gives me any credit, per sourcecred cred stuffs.

**Comment by hammadj** [comment]
> I appreciate the mention for copy pasting some of what I wrote, but I don’t think that actually gives me any credit, per sourcecred cred stuffs.

How can I attribute cred for this? Not sure exactly how the GitHub plugin works, was hoping the mention in issue description would be picked up.

**Comment by vsoch** [comment]
No worries @hammadj, the mention was very sweet.

**Comment by Beanow** [comment]
Actually, using mentions does flow a small amount of cred (small, because not all mentions are used to give credit to someone). You could use a stronger signal in commit messages with this:

`Paired with:`
https://github.com/sourcecred/sourcecred/blob/4309b624ec3a4772e97c79f3516909c75c3cbed1/src/plugins/github/README.md#edges

That will set the mentioned person as another author of that commit.

**Comment by Beanow** [comment]
> It would be great to have a search that does not have an additional dependency of an alogia account

Definitely agree with this. Especially from a privacy perspective ([their policy](https://www.algolia.com/policies/privacy/) is absolutely disgusting), would very much prefer to have a local search index using the likes of https://lunrjs.com/ and friends.

**Comment by hammadj** [comment]
> > It would be great to have a search that does not have an additional dependency of an alogia account
> 
> 
> 
> Definitely agree with this. Especially from a privacy perspective ([their policy](https://www.algolia.com/policies/privacy/) is absolutely disgusting), would very much prefer to have a local search index using the likes of https://lunrjs.com/ and friends.


https://github.com/cmfcmf/docusaurus-search-local

+1. Can use something like this. Offline search has been the top requested feature for docusaurus: https://v2.docusaurus.io/feedback/p/offline-search

**Pull request merged**
